namespace PRMS.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class initcse : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.CseEnrollments",
                c => new
                    {
                        id = c.Int(nullable: false, identity: true),
                        Name = c.String(),
                        StudentId = c.Int(nullable: false),
                        RegNo = c.Int(nullable: false),
                        Session = c.String(),
                        Semester = c.Int(nullable: false),
                        CSE_420 = c.Boolean(nullable: false),
                        CSE_421 = c.Boolean(nullable: false),
                        CCE_421 = c.Boolean(nullable: false),
                        CCE_422 = c.Boolean(nullable: false),
                        CIT_421 = c.Boolean(nullable: false),
                        CIT_422 = c.Boolean(nullable: false),
                        CIT_423 = c.Boolean(nullable: false),
                        CSE_410 = c.Boolean(nullable: false),
                        CSE_412 = c.Boolean(nullable: false),
                        CCE_411 = c.Boolean(nullable: false),
                        CCE_413 = c.Boolean(nullable: false),
                        CCE_415 = c.Boolean(nullable: false),
                        CCE_416 = c.Boolean(nullable: false),
                        CCE_417 = c.Boolean(nullable: false),
                        CIT_411 = c.Boolean(nullable: false),
                        CIT_412 = c.Boolean(nullable: false),
                        CIT_320 = c.Boolean(nullable: false),
                        CIT_321 = c.Boolean(nullable: false),
                        CIT_322 = c.Boolean(nullable: false),
                        CIT_323 = c.Boolean(nullable: false),
                        CIT_324 = c.Boolean(nullable: false),
                        EEE_321 = c.Boolean(nullable: false),
                        EEE_322 = c.Boolean(nullable: false),
                        CCE_320 = c.Boolean(nullable: false),
                        CCE_321 = c.Boolean(nullable: false),
                        CCE_322 = c.Boolean(nullable: false),
                        CCE_323 = c.Boolean(nullable: false),
                        CIT_311 = c.Boolean(nullable: false),
                        CIT_312 = c.Boolean(nullable: false),
                        CIT_313 = c.Boolean(nullable: false),
                        CIT_315 = c.Boolean(nullable: false),
                        CIT_316 = c.Boolean(nullable: false),
                        CCE_310 = c.Boolean(nullable: false),
                        CCE_311 = c.Boolean(nullable: false),
                        CCE_312 = c.Boolean(nullable: false),
                        CCE_313 = c.Boolean(nullable: false),
                        CCE_314 = c.Boolean(nullable: false),
                        CCE_221 = c.Boolean(nullable: false),
                        CCE_222 = c.Boolean(nullable: false),
                        CCE_223 = c.Boolean(nullable: false),
                        CCE_224 = c.Boolean(nullable: false),
                        AES_221 = c.Boolean(nullable: false),
                        MAT_221 = c.Boolean(nullable: false),
                        CIT_220 = c.Boolean(nullable: false),
                        CIT_221 = c.Boolean(nullable: false),
                        CIT_222 = c.Boolean(nullable: false),
                        CIT_224 = c.Boolean(nullable: false),
                        CIT_211 = c.Boolean(nullable: false),
                        CIT_212 = c.Boolean(nullable: false),
                        CIT_213 = c.Boolean(nullable: false),
                        CCE_212 = c.Boolean(nullable: false),
                        MAT_211 = c.Boolean(nullable: false),
                        EEE_211 = c.Boolean(nullable: false),
                        EEE_212 = c.Boolean(nullable: false),
                        AIS_211 = c.Boolean(nullable: false),
                        PHY_121 = c.Boolean(nullable: false),
                        PHY_122 = c.Boolean(nullable: false),
                        MAT_121 = c.Boolean(nullable: false),
                        CIT_121 = c.Boolean(nullable: false),
                        LCM_121 = c.Boolean(nullable: false),
                        EEE_121 = c.Boolean(nullable: false),
                        EEE_122 = c.Boolean(nullable: false),
                        CCE_121 = c.Boolean(nullable: false),
                        CCE_122 = c.Boolean(nullable: false),
                        CCE_124 = c.Boolean(nullable: false),
                        PHY_111 = c.Boolean(nullable: false),
                        PHY_112 = c.Boolean(nullable: false),
                        CHE_111 = c.Boolean(nullable: false),
                        CHE_112 = c.Boolean(nullable: false),
                        MAT_111 = c.Boolean(nullable: false),
                        EEE_111 = c.Boolean(nullable: false),
                        EEE_112 = c.Boolean(nullable: false),
                        CIT_111 = c.Boolean(nullable: false),
                        CIT_112 = c.Boolean(nullable: false),
                        CCE_112 = c.Boolean(nullable: false),
                    })
                .PrimaryKey(t => t.id);
            
            CreateTable(
                "dbo.JanCseEnrolments",
                c => new
                    {
                        id = c.Int(nullable: false, identity: true),
                        Name = c.String(),
                        StudentId = c.Int(nullable: false),
                        RegNo = c.Int(nullable: false),
                        Session = c.String(),
                        Semester = c.Int(nullable: false),
                        CSE_410 = c.Boolean(nullable: false),
                        CSE_412 = c.Boolean(nullable: false),
                        CCE_411 = c.Boolean(nullable: false),
                        CCE_413 = c.Boolean(nullable: false),
                        CCE_415 = c.Boolean(nullable: false),
                        CCE_416 = c.Boolean(nullable: false),
                        CCE_417 = c.Boolean(nullable: false),
                        CIT_411 = c.Boolean(nullable: false),
                        CIT_412 = c.Boolean(nullable: false),
                        CIT_311 = c.Boolean(nullable: false),
                        CIT_312 = c.Boolean(nullable: false),
                        CIT_313 = c.Boolean(nullable: false),
                        CIT_315 = c.Boolean(nullable: false),
                        CIT_316 = c.Boolean(nullable: false),
                        CCE_310 = c.Boolean(nullable: false),
                        CCE_311 = c.Boolean(nullable: false),
                        CCE_312 = c.Boolean(nullable: false),
                        CCE_313 = c.Boolean(nullable: false),
                        CCE_314 = c.Boolean(nullable: false),
                        CIT_211 = c.Boolean(nullable: false),
                        CIT_212 = c.Boolean(nullable: false),
                        CIT_213 = c.Boolean(nullable: false),
                        CCE_212 = c.Boolean(nullable: false),
                        MAT_211 = c.Boolean(nullable: false),
                        EEE_211 = c.Boolean(nullable: false),
                        EEE_212 = c.Boolean(nullable: false),
                        AIS_211 = c.Boolean(nullable: false),
                        PHY_111 = c.Boolean(nullable: false),
                        PHY_112 = c.Boolean(nullable: false),
                        CHE_111 = c.Boolean(nullable: false),
                        CHE_112 = c.Boolean(nullable: false),
                        MAT_111 = c.Boolean(nullable: false),
                        EEE_111 = c.Boolean(nullable: false),
                        EEE_112 = c.Boolean(nullable: false),
                        CIT_111 = c.Boolean(nullable: false),
                        CIT_112 = c.Boolean(nullable: false),
                        CCE_112 = c.Boolean(nullable: false),
                    })
                .PrimaryKey(t => t.id);
            
            CreateTable(
                "dbo.JuneCseEnrollments",
                c => new
                    {
                        id = c.Int(nullable: false, identity: true),
                        Name = c.String(),
                        StudentId = c.Int(nullable: false),
                        RegNo = c.Int(nullable: false),
                        Session = c.String(),
                        Semester = c.Int(nullable: false),
                        CSE_420 = c.Boolean(nullable: false),
                        CSE_421 = c.Boolean(nullable: false),
                        CCE_421 = c.Boolean(nullable: false),
                        CCE_422 = c.Boolean(nullable: false),
                        CIT_421 = c.Boolean(nullable: false),
                        CIT_422 = c.Boolean(nullable: false),
                        CIT_423 = c.Boolean(nullable: false),
                        CIT_320 = c.Boolean(nullable: false),
                        CIT_321 = c.Boolean(nullable: false),
                        CIT_322 = c.Boolean(nullable: false),
                        CIT_323 = c.Boolean(nullable: false),
                        CIT_324 = c.Boolean(nullable: false),
                        EEE_321 = c.Boolean(nullable: false),
                        EEE_322 = c.Boolean(nullable: false),
                        CCE_320 = c.Boolean(nullable: false),
                        CCE_321 = c.Boolean(nullable: false),
                        CCE_322 = c.Boolean(nullable: false),
                        CCE_323 = c.Boolean(nullable: false),
                        CCE_221 = c.Boolean(nullable: false),
                        CCE_222 = c.Boolean(nullable: false),
                        CCE_223 = c.Boolean(nullable: false),
                        CCE_224 = c.Boolean(nullable: false),
                        AES_221 = c.Boolean(nullable: false),
                        MAT_221 = c.Boolean(nullable: false),
                        CIT_220 = c.Boolean(nullable: false),
                        CIT_221 = c.Boolean(nullable: false),
                        CIT_222 = c.Boolean(nullable: false),
                        CIT_224 = c.Boolean(nullable: false),
                        PHY_121 = c.Boolean(nullable: false),
                        PHY_122 = c.Boolean(nullable: false),
                        MAT_121 = c.Boolean(nullable: false),
                        CIT_121 = c.Boolean(nullable: false),
                        LCM_121 = c.Boolean(nullable: false),
                        EEE_121 = c.Boolean(nullable: false),
                        EEE_122 = c.Boolean(nullable: false),
                        CCE_121 = c.Boolean(nullable: false),
                        CCE_122 = c.Boolean(nullable: false),
                        CCE_124 = c.Boolean(nullable: false),
                    })
                .PrimaryKey(t => t.id);
            
        }
        
        public override void Down()
        {
            DropTable("dbo.JuneCseEnrollments");
            DropTable("dbo.JanCseEnrolments");
            DropTable("dbo.CseEnrollments");
        }
    }
}
